{% set version = '1.2-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spacetime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spacetime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spacetime/spacetime_{{ version }}.tar.gz
  sha256: 1e9d3f92e5c4614a69c82a58bf0b5c829b4ed262bf1250bef943ae286056ea2d

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: adehabitatLT, cshapes, diveMove, foreign, gstat (>= 1.0-16), maps, mapdata, maptools, plm, raster, RColorBrewer, rgdal, rgeos, RPostgreSQL, knitr, googleVis, ISOcodes
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-intervals
    - r-lattice
    - r-sp >=1.1_0
    - r-xts >=0.8_8
    - r-zoo >=1.7_9

  run:
    - r-base
    - r-intervals
    - r-lattice
    - r-sp >=1.1_0
    - r-xts >=0.8_8
    - r-zoo >=1.7_9

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('spacetime')"           # [not win]
    - "\"%R%\" -e \"library('spacetime')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/edzer/spacetime
  license: GPL (>= 2)
  summary: Classes and methods for spatio-temporal data, including space-time regular lattices,
    sparse lattices, irregular data, and trajectories; utility functions for plotting
    data as map sequences (lattice or animation) or multiple time series; methods for
    spatial and temporal selection and subsetting, as well as for spatial/temporal/spatio-temporal
    matching or aggregation, retrieving coordinates, print, summary, etc.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: spacetime
# Version: 1.2-2
# Title: Classes and Methods for Spatio-Temporal Data
# Authors@R: c(person("Edzer", "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de", comment = c(ORCID = "0000-0001-8049-7069")), person("Benedikt", "Graeler", role = "ctb"), person("Tom", "Gottfried", role = "ctb"), person("Robert J.", "Hijmans", role = "ctb"))
# Depends: R (>= 3.0.0)
# Imports: graphics, utils, stats, methods, lattice, sp (>= 1.1-0), zoo (>= 1.7-9), xts (>= 0.8-8), intervals
# Suggests: adehabitatLT, cshapes, diveMove, foreign, gstat (>= 1.0-16), maps, mapdata, maptools, plm, raster, RColorBrewer, rgdal, rgeos, RPostgreSQL, knitr, googleVis, ISOcodes
# LazyData: no
# Description: Classes and methods for spatio-temporal data, including space-time regular lattices, sparse lattices, irregular data, and trajectories; utility functions for plotting data as map sequences (lattice or animation) or multiple time series; methods for spatial and temporal selection and subsetting, as well as for spatial/temporal/spatio-temporal matching or aggregation, retrieving coordinates, print, summary, etc.
# License: GPL (>= 2)
# URL: http://github.com/edzer/spacetime
# BugReports: https://github.com/edzer/spacetime/issues
# VignetteBuilder: knitr
# Collate: Class-xts.R Class-ST.R Class-STFDF.R Class-STSDF.R Class-STIDF.R Class-STTDF.R interval.R endtime.R ST-methods.R STFDF-methods.R STSDF-methods.R STIDF-methods.R STTDF-methods.R apply.R coerce.R stconstruct.R plot.R stplot.R timematch.R over.R aggregate.R eof.R mnf.R bind.R na.R raster.R tgrass.R stinteraction.R
# NeedsCompilation: no
# Packaged: 2018-07-17 07:29:41 UTC; edzer
# Author: Edzer Pebesma [aut, cre] (<https://orcid.org/0000-0001-8049-7069>), Benedikt Graeler [ctb], Tom Gottfried [ctb], Robert J. Hijmans [ctb]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Repository: CRAN
# Date/Publication: 2018-07-17 18:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
