{% set name = "pyezminc" %}
{% set version = "1.3.00" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/BIC-MNI/pyezminc.git
  git_rev: master-python3 [py3k]
  git_rev: master         [py2k]

build:
  number: 2
  script: "{{ PYTHON }} setup.py install "

requirements:
  host:
    - numpy
    - pip
    - python
    - cython
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
  build:
    - numpy
    - cython
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - setuptools
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
  run:
    - scipy
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
    - python
    - numpy

about:
  home: https://github.com/BIC-MNI/pyezminc
  license: GPL2
  summary: 'Python library for MINC IO, using cython and minc1 API'
  description: |
    Python library for MINC IO, using cython and minc1 API
  dev_url: https://github.com/BIC-MNI/pyezminc

extra:
  recipe-maintainers:
    - vfonov
