{% set version = '0.4.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survminer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survminer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survminer/survminer_{{ version }}.tar.gz
  sha256: 6eb91a39e52f930ea12b15adcdf7c578297ed9d31f0935e5debd79818fde522f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, flexsurv
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-broom
    - r-cmprsk
    - r-dplyr
    - r-ggplot2
    - r-ggpubr >=0.1.6
    - r-gridextra >=2.0
    - r-magrittr
    - r-maxstat
    - r-purrr
    - r-scales
    - r-survmisc
    - r-survival
    - r-tibble
    - r-tidyr

  run:
    - r-base
    - r-broom
    - r-cmprsk
    - r-dplyr
    - r-ggplot2
    - r-ggpubr >=0.1.6
    - r-gridextra >=2.0
    - r-magrittr
    - r-maxstat
    - r-purrr
    - r-scales
    - r-survmisc
    - r-survival
    - r-tibble
    - r-tidyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('survminer')"           # [not win]
    - "\"%R%\" -e \"library('survminer')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.sthda.com/english/rpkgs/survminer/
  license: GPL-2
  summary: Contains the function 'ggsurvplot()' for drawing easily beautiful and 'ready-to-publish'
    survival curves with the 'number at risk' table and 'censoring count plot'. Other
    functions are also available to plot  adjusted curves for `Cox` model and to visually
    examine 'Cox' model assumptions.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: survminer
# Type: Package
# Title: Drawing Survival Curves using 'ggplot2'
# Version: 0.4.3
# Date: 2018-08-04
# Authors@R: c( person("Alboukadel", "Kassambara", role = c("aut", "cre"), email = "alboukadel.kassambara@gmail.com"), person("Marcin", "Kosinski", role = c("aut"), email = "m.p.kosinski@@gmail.com"), person("Przemyslaw", "Biecek", role = c("ctb"), email = "przemyslaw.biecek@gmail.com"), person("Scheipl", "Fabian", role = c("ctb"), email = "fabian.scheipl@gmail.com"))
# Description: Contains the function 'ggsurvplot()' for drawing easily beautiful and 'ready-to-publish' survival curves with the 'number at risk' table and 'censoring count plot'. Other functions are also available to plot  adjusted curves for `Cox` model and to visually examine 'Cox' model assumptions.
# License: GPL-2
# LazyData: TRUE
# Depends: ggplot2, ggpubr(>= 0.1.6)
# Imports: grid, gridExtra(>= 2.0), magrittr, maxstat, methods, scales, survival, stats, broom, dplyr, tidyr, survMisc, cmprsk, purrr, tibble
# Suggests: knitr, flexsurv
# VignetteBuilder: knitr
# URL: http://www.sthda.com/english/rpkgs/survminer/
# BugReports: https://github.com/kassambara/survminer/issues
# RoxygenNote: 6.0.1
# Collate: 'BMT.R' 'BRCAOV.survInfo.R' 'add_ggsurvplot.R' 'utilities.R' 'surv_summary.R' 'ggsurvtable.R' 'surv_pvalue.R' 'ggsurvplot_df.R' 'ggsurvplot_core.R' 'ggsurvplot_add_all.R' 'ggsurvplot_list.R' 'ggsurvplot_group_by.R' 'ggsurvplot.R' 'arrange_ggsurvplots.R' 'ggadjustedcurves.R' 'ggcompetingrisks.R' 'ggcoxdiagnostics.R' 'ggcoxfunctional.R' 'ggcoxzph.R' 'ggflexsurvplot.R' 'ggforest.R' 'ggsurvevents.R' 'ggsurvplot_combine.R' 'ggsurvplot_facet.R' 'ggsurvtheme.R' 'ggurvplot_arguments.R' 'myeloma.R' 'pairwise_survdiff.R' 'surv_cutpoint.R' 'surv_group_by.R' 'surv_fit.R' 'surv_median.R'
# NeedsCompilation: no
# Packaged: 2018-08-04 14:00:41 UTC; kassambara
# Author: Alboukadel Kassambara [aut, cre], Marcin Kosinski [aut], Przemyslaw Biecek [ctb], Scheipl Fabian [ctb]
# Maintainer: Alboukadel Kassambara <alboukadel.kassambara@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-08-04 22:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
