package:
  name: minc-toolkit-v2-monolith
  version: "1.9.17"

source:
  url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.17-test/minc-toolkit-v2-2a5d2eac21e82c8ba36c2b6e4fa01e3b0e831668.tar.gz
  sha256: bb4112e4ca00313fc55495a20d275c0a69a242c5ecbad3425497ddba2f851a02

requirements:
  build:
    - cmake
    - flex
    - bison
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - {{ compiler('fortran') }}  [linux]
    - system                     [linux]
    - openblas=0.2.20
    - perl
  run:
    - perl
    - openblas

build:
  number: 0

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans (monolith package)'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2
  