{% set version = '0.3.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vctrs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vctrs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vctrs/vctrs_{{ version }}.tar.gz
  sha256: df7d368c9f2d2ad14872ba2a09821ec4f5a8ad77c81a0b05e1f440e5ffebad25

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, covr, crayon, dplyr (>= 0.8.5), generics, knitr, pillar (>= 1.4.4), pkgdown, rmarkdown, testthat (>= 2.3.0), tibble, withr, xml2, waldo (>= 0.2.0), zeallot
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-digest
    - r-ellipsis >=0.2.0
    - r-glue
    - r-rlang >=0.4.7

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-digest
    - r-ellipsis >=0.2.0
    - r-glue
    - r-rlang >=0.4.7

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('vctrs')"           # [not win]
    - "\"%R%\" -e \"library('vctrs')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://vctrs.r-lib.org/

  license: MIT
  summary: Defines new notions of prototype and size that are used to provide tools for consistent
    and well-founded type-coercion and size-recycling, and are in turn connected to
    ideas of type- and size-stability useful for analysing function interfaces.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: vctrs
# Title: Vector Helpers
# Version: 0.3.6
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = "aut", email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = c("aut", "cre"), email = "lionel@rstudio.com"), person(given = "Davis", family = "Vaughan", role = "aut", email = "davis@rstudio.com"), person(given = "data.table team", role = "cph", comment = "Radix sort based on data.table's forder() and their contribution to R's order()"), person(given = "RStudio", role = "cph"))
# Description: Defines new notions of prototype and size that are used to provide tools for consistent and well-founded type-coercion and size-recycling, and are in turn connected to ideas of type- and size-stability useful for analysing function interfaces.
# License: MIT + file LICENSE
# URL: https://vctrs.r-lib.org/
# BugReports: https://github.com/r-lib/vctrs/issues
# Depends: R (>= 3.3)
# Imports: ellipsis (>= 0.2.0), digest, glue, rlang (>= 0.4.7)
# Suggests: bit64, covr, crayon, dplyr (>= 0.8.5), generics, knitr, pillar (>= 1.4.4), pkgdown, rmarkdown, testthat (>= 2.3.0), tibble, withr, xml2, waldo (>= 0.2.0), zeallot
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-GB
# LazyData: true
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2020-12-17 09:22:46 UTC; lionel
# Author: Hadley Wickham [aut], Lionel Henry [aut, cre], Davis Vaughan [aut], data.table team [cph] (Radix sort based on data.table's forder() and their contribution to R's order()), RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-12-17 10:30:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
