{% set version = '0.3.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ellipsis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ellipsis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ellipsis/ellipsis_{{ version }}.tar.gz
  sha256: 4f8a15158dfc27cdc0f7554c7a61e92b02e4d70bfc3d968f01a99da2189b75db

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, testthat
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-rlang >=0.3.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rlang >=0.3.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ellipsis')"           # [not win]
    - "\"%R%\" -e \"library('ellipsis')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://ellipsis.r-lib.org, https://github.com/r-lib/ellipsis

  license: GPL-3
  summary: 'The ellipsis is a powerful tool for extending functions. Unfortunately this power
    comes at a cost: misspelled arguments will be silently ignored. The ellipsis package
    provides a collection of functions to catch problems and alert the user.'

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: ellipsis
# Version: 0.3.1
# Title: Tools for Working with ...
# Description: The ellipsis is a powerful tool for extending functions. Unfortunately this power comes at a cost: misspelled arguments will be silently ignored. The ellipsis package provides a collection of functions to catch problems and alert the user.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# URL: https://ellipsis.r-lib.org, https://github.com/r-lib/ellipsis
# BugReports: https://github.com/r-lib/ellipsis/issues
# Depends: R (>= 3.2)
# Imports: rlang (>= 0.3.0)
# Suggests: covr, testthat
# NeedsCompilation: yes
# Packaged: 2020-05-15 05:57:33 UTC; lionel
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-05-15 14:10:06 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
