{% set version = '3.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mice/mice_{{ version }}.tar.gz
  sha256: f53163ba807822b73c38bf93df557f194158cd4e87dd2362ed73fc2483acaa65

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: AGD, CALIBERrfimpute, DPpackage, gamlss, lme4, mitools, nlme, pan, randomForest, Zelig, BSDA, knitr, rmarkdown, testthat, HSAUR3, micemd, miceadds, tidyr
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-broom
    - r-dplyr
    - r-lattice
    - r-mitml
    - r-nnet
    - r-rlang
    - r-rpart
    - r-survival

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-rcpp
    - r-broom
    - r-dplyr
    - r-lattice
    - r-mitml
    - r-nnet
    - r-rlang
    - r-rpart
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mice')"           # [not win]
    - "\"%R%\" -e \"library('mice')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://stefvanbuuren.github.io/mice/ , http://www.stefvanbuuren.name , http://www.stefvanbuuren.name/fimd/
  license: GPL-2 | GPL-3
  summary: Multiple imputation using Fully Conditional Specification (FCS) implemented by the
    MICE algorithm as described in Van Buuren and Groothuis-Oudshoorn (2011) <doi:10.18637/jss.v045.i03>.
    Each variable has its own imputation model. Built-in imputation models are provided
    for continuous data (predictive mean matching, normal), binary data (logistic regression),
    unordered categorical data (polytomous logistic regression) and ordered categorical
    data (proportional odds). MICE can also impute continuous two-level data (normal
    model, pan, second-level variables). Passive imputation can be used to maintain
    consistency between variables. Various diagnostic plots are available to inspect
    the quality of the imputations.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: mice
# Type: Package
# Version: 3.4.0
# Title: Multivariate Imputation by Chained Equations
# Date: 2019-03-06
# Authors@R: c(person("Stef", "van Buuren", role = c("aut","cre"), email = "stef.vanbuuren@tno.nl"), person("Karin", "Groothuis-Oudshoorn", role = "aut", email = "c.g.m.oudshoorn@utwente.nl"), person("Alexander", "Robitzsch", role = "ctb", email = "robitzsch@ipn.uni-kiel.de"), person("Gerko","Vink", role = "ctb", email = "g.vink@uu.nl"), person("Lisa","Doove", role = "ctb", email = "lisa.doove@ppw.kuleuven.be"), person("Shahab","Jolani", role = "ctb", email = "s.jolani@maastrichtuniversity.nl"), person("Rianne","Schouten", role = "ctb", email = "R.M.Schouten@uu.nl"), person("Philipp","Gaffert", role = "ctb", email = "philipp.gaffert@gfk.com"), person("Florian","Meinfelder", role = "ctb", email = "florian.meinfelder@uni-bamberg.de"), person("Bernie","Gray", role = "ctb", email = "bfgray3@gmail.com"))
# Maintainer: Stef van Buuren <stef.vanbuuren@tno.nl>
# Depends: methods, R (>= 2.10.0), lattice
# Imports: broom, dplyr, grDevices, graphics, MASS, mitml, nnet, parallel, Rcpp, rlang, rpart, splines, stats, survival, utils
# Suggests: AGD, CALIBERrfimpute, DPpackage, gamlss, lme4, mitools, nlme, pan, randomForest, Zelig, BSDA, knitr, rmarkdown, testthat, HSAUR3, micemd, miceadds, tidyr
# LinkingTo: Rcpp
# Description: Multiple imputation using Fully Conditional Specification (FCS) implemented by the MICE algorithm as described in Van Buuren and Groothuis-Oudshoorn (2011) <doi:10.18637/jss.v045.i03>. Each variable has its own imputation model. Built-in imputation models are provided for continuous data (predictive mean matching, normal), binary data (logistic regression), unordered categorical data (polytomous logistic regression) and ordered categorical data (proportional odds). MICE can also impute continuous two-level data (normal model, pan, second-level variables). Passive imputation can be used to maintain consistency between variables. Various diagnostic plots are available to inspect the quality of the imputations.
# License: GPL-2 | GPL-3
# LazyLoad: yes
# LazyData: yes
# URL: http://stefvanbuuren.github.io/mice/ , http://www.stefvanbuuren.name , http://www.stefvanbuuren.name/fimd/
# BugReports: https://github.com/stefvanbuuren/mice/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-03-07 07:45:28 UTC; buurensv
# Author: Stef van Buuren [aut, cre], Karin Groothuis-Oudshoorn [aut], Alexander Robitzsch [ctb], Gerko Vink [ctb], Lisa Doove [ctb], Shahab Jolani [ctb], Rianne Schouten [ctb], Philipp Gaffert [ctb], Florian Meinfelder [ctb], Bernie Gray [ctb]
# Repository: CRAN
# Date/Publication: 2019-03-07 09:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
