{% set version = '0.9.22' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rptr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rptR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rptR/rptR_{{ version }}.tar.gz
  sha256: 3365b1202fd6a4a5585fe17e975f1de4ba800d30ff1c3a192f2d1c1cb161726f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-lme4
    - r-pbapply

  run:
    - r-base
    - r-lme4
    - r-pbapply

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rptR')"           # [not win]
    - "\"%R%\" -e \"library('rptR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rptR
  license: GPL (>= 2)
  summary: Estimating repeatability (intra-class correlation) from Gaussian, binary, proportion
    and Poisson data.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: rptR
# Title: Repeatability Estimation for Gaussian and Non-Gaussian Data
# Version: 0.9.22
# Depends: R (>= 3.2.1)
# Date: 2019-06-03
# Author: Martin Stoffel <martin.adam.stoffel@gmail.com>, Shinichi Nakagawa <s.nakagawa@unsw.edu.au>, Holger Schielzeth <holger.schielzeth@uni-jena.de>
# Maintainer: Martin Stoffel <martin.adam.stoffel@gmail.com>
# Description: Estimating repeatability (intra-class correlation) from Gaussian, binary, proportion and Poisson data.
# License: GPL (>= 2)
# Imports: methods, stats, lme4, parallel (>= 3.1.2), pbapply
# Suggests: testthat, knitr, rmarkdown
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-06 15:13:44 UTC; martin
# Repository: CRAN
# Date/Publication: 2019-03-06 22:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
