{% set version = '1.5-7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geosphere
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geosphere_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geosphere/geosphere_{{ version }}.tar.gz
  sha256: 9d9b555e2d59a5ae174ae654652121f169fbc3e9cf66c2491bfbe0684b6dd8a0

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: methods, raster
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-sp

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-sp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('geosphere')"           # [not win]
    - "\"%R%\" -e \"library('geosphere')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=geosphere
  license: GPL (>= 3)
  summary: 'Spherical trigonometry for geographic applications. That is, compute distances and
    related measures for angular (longitude/latitude) locations. '

  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: geosphere
# Type: Package
# Title: Spherical Trigonometry
# Version: 1.5-7
# Date: 2017-11-02
# Imports: sp
# Depends: R (>= 3.0.0)
# Suggests: methods, raster
# Authors@R: c( person("Robert J.", "Hijmans", role = c("cre", "aut"),  email = "r.hijmans@gmail.com"), person("Ed", "Williams", role = "ctb"), person("Chris", "Vennes", role = "ctb"))
# Description: Spherical trigonometry for geographic applications. That is, compute distances and related measures for angular (longitude/latitude) locations.
# License: GPL (>= 3)
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2017-11-03 07:22:06 UTC; rhijmans
# Author: Robert J. Hijmans [cre, aut], Ed Williams [ctb], Chris Vennes [ctb]
# Maintainer: Robert J. Hijmans <r.hijmans@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-11-05 18:42:40 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
