{% set name = "RMINC" %}
{% set version = "1.5.2.2" %}

# probably will not wotk on windows anyway 
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/vfonov/RMINC/archive/develop-tidy.tar.gz
  sha256: 2d6f23532953bf9a24d42e6c7028efda11e08244f42581aed64243007806be09

build:
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - {{ compiler('fortran') }}  [linux]
    - r-base {{ r_base }}
    - r-dplyr
    - r-batchtools
    - r-tidyr
    - r-readr
    - r-lme4
    - r-purrr
    - r-shiny
    - r-gridbase
    - r-Rcpp
    - r-Matrix
    - r-tibble
    - r-yaml
    - r-data.tree
    - r-visNetwork
    - r-rjson
    - r-DT
    - r-rlang
    - minc-toolkit-v2
    - zlib

  build:
    - {{posix}}make
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - {{ compiler('fortran') }}  [linux]
    - minc-toolkit-v2
    - r-base {{ r_base }}
    - zlib

  run:
    - minc-toolkit-v2
    - zlib
    - r-base {{ r_base }}
    - r-dplyr
    - r-batchtools
    - r-tidyr
    - r-readr
    - r-lme4
    - r-purrr
    - r-shiny
    - r-gridbase
    - r-Rcpp
    - r-Matrix
    - r-tibble
    - r-yaml
    - r-data.tree
    - r-visNetwork
    - r-rjson
    - r-DT
    - r-rlang

about:
  home: https://github.com/Mouse-Imaging-Centre/RMINC
  summary: 'MINC inteface to R'
  dev_url: https://github.com/Mouse-Imaging-Centre/RMINC

extra:
  recipe-maintainers:
    - vfonov
