{% set version = '0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatialwidget
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatialwidget_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatialwidget/spatialwidget_{{ version }}.tar.gz
  sha256: e296b12ab78f2819402b78b36eaecb8e90bb7f776351bfd2ac77e046b67eb780

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: colourvalues, covr, geojsonsf, jsonify, jsonlite, knitr, rmarkdown, sf, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-colourvalues >=0.2.2
    - r-geojsonsf >=1.3.0
    - r-jsonify >=0.2.0
    - r-rapidjsonr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rcpp
    - r-colourvalues >=0.2.2
    - r-geojsonsf >=1.3.0
    - r-jsonify >=0.2.0
    - r-rapidjsonr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('spatialwidget')"           # [not win]
    - "\"%R%\" -e \"library('spatialwidget')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://symbolixau.github.io/spatialwidget/articles/spatialwidget.html
  license: GPL-3
  summary: 'Many packages use ''htmlwidgets'' <https://CRAN.R-project.org/package=htmlwidgets>
    for interactive plotting of spatial data. This package provides functions for converting
    R objects, such as simple features,  into structures suitable for use in ''htmlwidgets''
    mapping libraries. '

  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: spatialwidget
# Type: Package
# Title: Converts Spatial Data to Javascript Object Notation (JSON) for Use in Htmlwidgets
# Version: 0.2
# Date: 2019-01-18
# Authors@R: c( person("David", "Cooley", ,"dcooley@symbolix.com.au", role = c("aut", "cre")) )
# Description: Many packages use 'htmlwidgets' <https://CRAN.R-project.org/package=htmlwidgets> for interactive plotting of spatial data. This package provides functions for converting R objects, such as simple features,  into structures suitable for use in 'htmlwidgets' mapping libraries.
# URL: https://symbolixau.github.io/spatialwidget/articles/spatialwidget.html
# License: GPL-3
# Depends: R (>= 3.3.0)
# Encoding: UTF-8
# LazyData: true
# Imports: Rcpp
# LinkingTo: BH, colourvalues (>= 0.2.2), geojsonsf (>= 1.3.0), jsonify (>= 0.2.0), rapidjsonr, Rcpp
# RoxygenNote: 6.1.1
# Suggests: colourvalues, covr, geojsonsf, jsonify, jsonlite, knitr, rmarkdown, sf, testthat
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-01-18 09:15:18 UTC; dave
# Author: David Cooley [aut, cre]
# Maintainer: David Cooley <dcooley@symbolix.com.au>
# Repository: CRAN
# Date/Publication: 2019-01-18 09:40:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
