bzip2:
- '1'
cuda_compiler_version:
- None
gflags:
- '2.2'
glog:
- 0.4.0
lz4_c:
- 1.9.2
# python:
# - '3.8'
# numpy:
# - '1.16'
grpc_cpp:
- '1.34'
libprotobuf:
- '3.14'
pin_run_as_build:
  bzip2:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
re2:
- 2020.11.01
snappy:
- '1'
target_platform:
- linux-64
