{% set version = '0.1-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lwgeom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lwgeom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lwgeom/lwgeom_{{ version }}.tar.gz
  sha256: bb45d30d6ad3c70c0dbaa1b9eb3185d413303fee77272240108fda12b26817eb

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, sp, geosphere, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-sf >=0.6_0
    - r-units

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-sf >=0.6_0
    - r-units

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lwgeom')"           # [not win]
    - "\"%R%\" -e \"library('lwgeom')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-spatial/lwgeom/
  license: GPL-2
  summary: Access to selected functions found in 'liblwgeom' <https://github.com/postgis/postgis/tree/svn-trunk/liblwgeom>,
    the light-weight geometry library used by 'PostGIS' <http://postgis.net/>.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: lwgeom
# Version: 0.1-5
# Title: Bindings to Selected 'liblwgeom' Functions for Simple Features
# Description: Access to selected functions found in 'liblwgeom' <https://github.com/postgis/postgis/tree/svn-trunk/liblwgeom>, the light-weight geometry library used by 'PostGIS' <http://postgis.net/>.
# Authors@R: c(person("Edzer", "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de", comment = c(ORCID = "0000-0001-8049-7069")), person("Colin", "Rundel", role = "ctb"), person("Andy", "Teucher", role = "ctb"), person("liblwgeom developers", role = "cph"))
# Depends: R (>= 3.3.0)
# Imports: Rcpp, units, sf (>= 0.6-0)
# Suggests: covr, sp, geosphere, testthat
# LinkingTo: Rcpp, sf (>= 0.6-0)
# SystemRequirements: GEOS (>= 3.3.0), PROJ (>= 4.8.0)
# License: GPL-2
# Copyright: file COPYRIGHTS
# URL: https://github.com/r-spatial/lwgeom/
# BugReports: https://github.com/r-spatial/lwgeom/issues/
# Collate: init.R RcppExports.R geohash.R split.R subdivide.R valid.R transform.R bounding_circle.R bearing.R snap_to_grid.R startpoint.R twkb.R perimeter.R clockwise.R geod.R wkt.R
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-12-05 19:57:20 UTC; edzer
# Author: Edzer Pebesma [aut, cre] (<https://orcid.org/0000-0001-8049-7069>), Colin Rundel [ctb], Andy Teucher [ctb], liblwgeom developers [cph]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Repository: CRAN
# Date/Publication: 2018-12-07 09:40:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
