package:
  name: cortex_walk
  version: "0.0.1"

source:
  #git_url: https://github.com/vfonov/cortex_walk.git
  #git_rev: f9fafcc084cc2e9f6ca00efdbd4de8d198d3c98e
  path: ../../cortex_walk/


requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
  run:
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}

test:
  commands:
    - cortex_walk --help


build:
  number: 0

about:
  home: https://github.com/vfonov/cortex_walk
  license: GPL3
  summary: 'Cortex walk tool'
  description: |
    A simple tool for walking the surface
