package:
  name: falcon
  version: "0.9.0"

source:
  url: https://github.com/vfonov/falcon/archive/release-0.9.00.tar.gz
  sha256: fc822d99d85edfeab63258dd99bc3fdde73feb3fefc777fa8eabdc09b646b31b

requirements:
  build:
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
    - libtiff
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
  run: 
    - libtiff
    - povray
    - imagemagick
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}

test:
  commands:
    - falcon_cortex_initocs --version
    - falcon_cortex_initics --version
    - falcon_cortex_refine -help

build:
  number: 0


about:
  home: https://github.com/vfonov/falcon
  license: GPL3
  summary: 'Falcon cortical thickness measurement'
  description: |
    Falcon is a set of tools for cortical thickness measurements, to be made public sometime soon.
