package:
  name: falcon
  version: "0.1.2"

source:
  path: ../../falcon/

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
    - minc-toolkit-v2
    - libtiff
  run:
    - minc-toolkit-v2
    - povray
    - libtiff
    - imagemagick
test:
  commands:
    - falcon_cortex_initocs --version
    - falcon_cortex_initics --version
    - falcon_cortex_refine -help


build:
  number: 3

about:
  home: https://github.com/vfonov/falcon
  license: GPL3
  summary: 'Falcon cortical thickness measurement'
  description: |
    Falcon is a set of tools for cortical thickness measurements, to be made public sometime soon.
