{% set version = '0.1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bigassertr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bigassertr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bigassertr/bigassertr_{{ version }}.tar.gz
  sha256: a909e4d8b7e6579faba6163d9a3561ea02998c5f7682ea2cca79b61ef55e0ab8

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, covr
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bigassertr')"           # [not win]
    - "\"%R%\" -e \"library('bigassertr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/privefl/bigassertr

  license: GPL-3
  summary: Enhanced message functions (cat() / message() / warning() / error()) using wrappers
    around sprintf(). Also, multiple assertion functions (e.g. to check class, length,
    values, files, arguments, etc.).

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: bigassertr
# Title: Assertion and Message Functions
# Version: 0.1.3
# Date: 2020-04-01
# Authors@R: person(given = "Florian", family = "Prive", role = c("aut", "cre"), email = "florian.prive.21@gmail.com")
# Description: Enhanced message functions (cat() / message() / warning() / error()) using wrappers around sprintf(). Also, multiple assertion functions (e.g. to check class, length, values, files, arguments, etc.).
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# Suggests: testthat, covr
# URL: https://github.com/privefl/bigassertr
# BugReports: https://github.com/privefl/bigassertr/issues
# NeedsCompilation: no
# Packaged: 2020-04-01 10:39:35 UTC; au639593
# Author: Florian Prive [aut, cre]
# Maintainer: Florian Prive <florian.prive.21@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-04-01 11:10:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
