{% set version = '0.2.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-broom.mixed
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/broom.mixed_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broom.mixed/broom.mixed_{{ version }}.tar.gz
  sha256: 798526a69eafcd014af943ca63b01e551f9ffa534979c474e1b9b0bda1e44538

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat, ggplot2, Matrix, MCMCglmm, lme4, rstan, rstanarm, brms, mgcv, gamlss, lmerTest, glmmADMB, dotwhisker, pander
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-tmb
    - r-broom
    - r-coda
    - r-dplyr
    - r-glmmtmb
    - r-nlme
    - r-plyr
    - r-purrr
    - r-reshape2
    - r-stringr
    - r-tibble
    - r-tidyr

  run:
    - r-base
    - r-tmb
    - r-broom
    - r-coda
    - r-dplyr
    - r-glmmtmb
    - r-nlme
    - r-plyr
    - r-purrr
    - r-reshape2
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('broom.mixed')"           # [not win]
    - "\"%R%\" -e \"library('broom.mixed')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/bbolker/broom.mixed
  license: GPL-3
  summary: 'Convert fitted objects from various R mixed-model packages into tidy data frames
    along the lines of the ''broom'' package. The package provides three S3 generics
    for each model: tidy(), which summarizes a model''s statistical findings such as
    coefficients of a regression; augment(), which adds columns to the original data
    such as predictions, residuals and cluster assignments; and glance(), which provides
    a one-row summary of model-level statistics.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: broom.mixed
# Type: Package
# Title: Tidying Methods for Mixed Models
# Version: 0.2.3
# Authors@R: c( person("Ben", "Bolker", email = "bolker@mcmaster.ca", role = c("aut", "cre"), comment=c(ORCID="0000-0002-2127-0443")), person("David", "Robinson", email = "admiral.david@gmail.com", role = "aut"), person("Dieter", "Menne", role = "ctb"), person("Jonah", "Gabry", role = "ctb"), person("Paul", "Buerkner", role = "ctb"), person("Christopher", "Hua", role = "ctb"), person("Will", "Petry", role = "ctb"), person("Josh", "Wiley", role = "ctb"), person("Patrick", "Kennedy", role = "ctb") )
# Maintainer: Ben Bolker <bolker@mcmaster.ca>
# Description: Convert fitted objects from various R mixed-model packages into tidy data frames along the lines of the 'broom' package. The package provides three S3 generics for each model: tidy(), which summarizes a model's statistical findings such as coefficients of a regression; augment(), which adds columns to the original data such as predictions, residuals and cluster assignments; and glance(), which provides a one-row summary of model-level statistics.
# Depends: R (>= 3.5.0)
# Imports: broom, dplyr, tidyr, plyr, purrr, tibble, reshape2, nlme, methods, stringr, coda, glmmTMB, TMB
# Suggests: knitr, testthat, ggplot2, Matrix, MCMCglmm, lme4, rstan, rstanarm, brms, mgcv, gamlss, lmerTest, glmmADMB, dotwhisker, pander
# URL: http://github.com/bbolker/broom.mixed
# BugReports: http://github.com/bbolker/broom.mixed/issues
# License: GPL-3
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# Additional_repositories: http://bbolker.github.io/drat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-10-21 18:43:06 UTC; bolker
# Author: Ben Bolker [aut, cre] (<https://orcid.org/0000-0002-2127-0443>), David Robinson [aut], Dieter Menne [ctb], Jonah Gabry [ctb], Paul Buerkner [ctb], Christopher Hua [ctb], Will Petry [ctb], Josh Wiley [ctb], Patrick Kennedy [ctb]
# Repository: CRAN
# Date/Publication: 2018-10-21 21:40:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
