{% set version = '0.3.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openstreetmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/OpenStreetMap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/OpenStreetMap/OpenStreetMap_{{ version }}.tar.gz
  sha256: 61a0c711d91e61b8e77c0693112798e5005bafd3154ba29632d6a0d82909db4f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: colorspace, maptools
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-ggplot2 >=0.9.0
    - r-rjava
    - r-raster
    - r-rgdal
    - r-sp

  run:
    - r-base
    - r-ggplot2 >=0.9.0
    - r-rjava
    - r-raster
    - r-rgdal
    - r-sp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('OpenStreetMap')"           # [not win]
    - "\"%R%\" -e \"library('OpenStreetMap')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.fellstat.com http://blog.fellstat.com/?cat=15
  license: GPL-2 | file LICENCE
  summary: Accesses high resolution raster maps using the OpenStreetMap protocol. Dozens of road,
    satellite, and topographic map servers are directly supported, including Apple,
    Mapnik, Bing, and stamen. Additionally raster maps may be constructed using custom
    tile servers.  Maps can be plotted using either base graphics, or ggplot2. This
    package is not affiliated with the OpenStreetMap.org mapping project.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: OpenStreetMap
# Maintainer: Ian Fellows <ian@fellstat.com>
# License: GPL-2 | file LICENCE
# Title: Access to Open Street Map Raster Images
# Author: Ian Fellows, using the JMapViewer library by Jan Peter Stotz
# Description: Accesses high resolution raster maps using the OpenStreetMap protocol. Dozens of road, satellite, and topographic map servers are directly supported, including Apple, Mapnik, Bing, and stamen. Additionally raster maps may be constructed using custom tile servers.  Maps can be plotted using either base graphics, or ggplot2. This package is not affiliated with the OpenStreetMap.org mapping project.
# SystemRequirements: Java (>= 1.5), JRI
# Version: 0.3.3
# URL: http://www.fellstat.com http://blog.fellstat.com/?cat=15
# Date: 2016-09-09
# Depends: methods, R (>= 2.10.0)
# Suggests: colorspace, maptools
# Imports: grDevices, ggplot2 (>= 0.9.0), rJava, raster, rgdal, sp
# Collate: 'OpenStreetMap-package.R' 'osm.R' 'autoplot.R' 'zzz.R'
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-09-09 17:32:31 UTC; ianfellows
# Repository: CRAN
# Date/Publication: 2016-09-09 23:49:52

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
