package:
  name: jq
  version: "1.6"

source:
  fn: jq-1.6.tar.gz
  url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz
  sha256: 5de8c8e29aaa3fb9cc6b47bb27299f271354ebb72514e3accadc7d38b5bbaa72

requirements:
  build:
    - bison
    - {{ compiler('c') }}
    - make
    - oniguruma
  host:
    - oniguruma
  run:
    - oniguruma

test:
  commands:
  - jq --help  # [not win]

build:
  number: 0

about:
  home: https://stedolan.github.io/jq/
  summary: 'jq is a lightweight and flexible command-line JSON processor.'
  license: MIT
