{% set version = '0.4-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-classint
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/classInt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/classInt/classInt_{{ version }}.tar.gz
  sha256: bb0da1e7db779831cf5cea80722ade90bf83a9aa51b7d2bc6bee69c433042871

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: spData (>= 0.2.6.2), units
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-kernsmooth
    - r-class
    - r-e1071

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-kernsmooth
    - r-class
    - r-e1071

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('classInt')"           # [not win]
    - "\"%R%\" -e \"library('classInt')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-spatial/classInt/
  license: GPL-2
  summary: Selected commonly used methods for choosing univariate class intervals for mapping
    or other graphics purposes.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: classInt
# Version: 0.4-2
# Date: 2019-10-17
# Title: Choose Univariate Class Intervals
# Authors@R: c( person("Roger", "Bivand", role=c("aut", "cre"), email="Roger.Bivand@nhh.no", comment=c(ORCID="0000-0003-2392-6140")), person("Hisaji", "Ono", role="ctb"), person("Richard", "Dunlap", role="ctb"), person("Matthieu", "Stigler", role="ctb"), person("Bill", "Denney", role="ctb", email="wdenney@humanpredictions.com", comment=c(ORCID="0000-0002-5759-428X")))
# Depends: R (>= 2.2)
# Imports: grDevices, stats, graphics, e1071, class, KernSmooth
# Suggests: spData (>= 0.2.6.2), units
# NeedsCompilation: yes
# Description: Selected commonly used methods for choosing univariate class intervals for mapping or other graphics purposes.
# License: GPL (>= 2)
# URL: https://github.com/r-spatial/classInt/
# BugReports: https://github.com/r-spatial/classInt/issues/
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# Packaged: 2019-10-17 08:13:18 UTC; rsb
# Author: Roger Bivand [aut, cre] (<https://orcid.org/0000-0003-2392-6140>), Hisaji Ono [ctb], Richard Dunlap [ctb], Matthieu Stigler [ctb], Bill Denney [ctb] (<https://orcid.org/0000-0002-5759-428X>)
# Maintainer: Roger Bivand <Roger.Bivand@nhh.no>
# Repository: CRAN
# Date/Publication: 2019-10-17 19:00:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
