{% set version = '1.3-9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polynom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/polynom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/polynom/polynom_{{ version }}.tar.gz
  sha256: d35a50925cc5552a6aac0816a91dbc03e9fd77da47e06d27572fde9dcbee9de8

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('polynom')"           # [not win]
    - "\"%R%\" -e \"library('polynom')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=polynom
  license: GPL-2
  summary: A collection of functions to implement a class for univariate polynomial manipulations.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: polynom
# Version: 1.3-9
# Title: A Collection of Functions to Implement a Class for Univariate Polynomial Manipulations
# Authors@R: c(person("Bill", "Venables", role = "aut", email = "Bill.Venables@adelaide.edu.au", comment = "S original"), person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = "R port"), person("Martin", "Maechler", role = "aut", email = "maechler@stat.math.ethz.ch", comment = "R port"))
# Description: A collection of functions to implement a class for univariate polynomial manipulations.
# Imports: stats, graphics
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2016-12-08 19:08:48 UTC; hornik
# Author: Bill Venables [aut] (S original), Kurt Hornik [aut, cre] (R port), Martin Maechler [aut] (R port)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2016-12-08 20:22:36

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
