{% set version = '0.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggsignif
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggsignif_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggsignif/ggsignif_{{ version }}.tar.gz
  sha256: c7a1d3155cd848d008762a7aa15453e6f09fa7f719c60899995d8d754f43c5e6

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-ggplot2 >=2.0.0

  run:
    - r-base
    - r-ggplot2 >=2.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ggsignif')"           # [not win]
    - "\"%R%\" -e \"library('ggsignif')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/const-ae/ggsignif
  license: GPL-3
  summary: Enrich your 'ggplots' with group-wise comparisons. This package provides an easy way
    to indicate if two groups are significantly different. Commonly this is shown by
    a bracket on top connecting the groups of interest which itself is annotated with
    the level of significance (NS, *, **, ***). The package provides a single layer
    (geom_signif()) that takes the groups for comparison and the test (t.test(), wilcox.text()
    etc.) as arguments and adds the annotation to the plot.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: ggsignif
# Type: Package
# Title: Significance Brackets for 'ggplot2'
# Version: 0.4.0
# Authors@R: person("Constantin", "Ahlmann-Eltze", email = "artjom31415@googlemail.com", role = c("aut", "cre"))
# Description: Enrich your 'ggplots' with group-wise comparisons. This package provides an easy way to indicate if two groups are significantly different. Commonly this is shown by a bracket on top connecting the groups of interest which itself is annotated with the level of significance (NS, *, **, ***). The package provides a single layer (geom_signif()) that takes the groups for comparison and the test (t.test(), wilcox.text() etc.) as arguments and adds the annotation to the plot.
# URL: https://github.com/const-ae/ggsignif
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: ggplot2 (>= 2.0.0)
# Suggests: testthat, knitr, rmarkdown
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2017-08-03 09:46:19 UTC; constantin
# Author: Constantin Ahlmann-Eltze [aut, cre]
# Maintainer: Constantin Ahlmann-Eltze <artjom31415@googlemail.com>
# Repository: CRAN
# Date/Publication: 2017-08-03 14:35:48 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
