{% set name = "minc2-simple" %}
{% set version = "0.2.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/vfonov/minc2-simple/archive/v2.1.tar.gz
  sha256: d0a72f423943106cadc364bd775ee2bbf06d37f88d5ac94c8e0a80a4981f3ba7

build:
  number: 0
  script: "{{ PYTHON }} python/setup.py install "

requirements:
  host:
    - numpy
    - pip
    - python
    - minc-toolkit-v2
    - cffi
    - six
  build:
    - numpy
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - setuptools
    - minc-toolkit-v2
  run:
    - minc-toolkit-v2
    - python
    - numpy
    - six
    - cffi

about:
  home: https://github.com/BIC-MNI/pyezminc
  license: GPL2
  summary: 'Python library for MINC IO, using minc2 API and CFFI'
  description: |
    Python library for MINC IO, using minc2 API and CFFI
  dev_url: https://github.com/BIC-MNI/pyezminc

extra:
  recipe-maintainers:
    - vfonov
