{% set version = '1.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fs/fs_{{ version }}.tar.gz
  sha256: 36df1653571de3c628a4f769c4627f6ac53d0f9e4106d9d476afb22ae9603897

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, covr, pillar (>= 1.0.0), tibble (>= 1.1.0), crayon, rmarkdown, knitr, withr, spelling, vctrs (>= 0.3.0)
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fs')"           # [not win]
    - "\"%R%\" -e \"library('fs')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://fs.r-lib.org, https://github.com/r-lib/fs

  license: GPL-3
  summary: A cross-platform interface to file system operations, built on top of the 'libuv'
    C library.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: fs
# Title: Cross-Platform File System Operations Based on 'libuv'
# Version: 1.5.0
# Authors@R: c( person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("libuv project contributors", role = "cph", comment = "libuv library"), person("Joyent, Inc. and other Node contributors", role = "cph", comment = "libuv library"), person("RStudio", role = c("cph", "fnd")) )
# Description: A cross-platform interface to file system operations, built on top of the 'libuv' C library.
# Depends: R (>= 3.1)
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# Imports: methods
# SystemRequirements: GNU make
# RoxygenNote: 7.1.1
# URL: http://fs.r-lib.org, https://github.com/r-lib/fs
# BugReports: https://github.com/r-lib/fs/issues
# Copyright: file COPYRIGHTS
# Suggests: testthat, covr, pillar (>= 1.0.0), tibble (>= 1.1.0), crayon, rmarkdown, knitr, withr, spelling, vctrs (>= 0.3.0)
# VignetteBuilder: knitr
# Language: en-US
# NeedsCompilation: yes
# Packaged: 2020-07-31 21:00:55 UTC; jhester
# Author: Jim Hester [aut, cre], Hadley Wickham [aut], libuv project contributors [cph] (libuv library), Joyent, Inc. and other Node contributors [cph] (libuv library), RStudio [cph, fnd]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-07-31 21:30:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
