{% set version = '0.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quadmesh
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quadmesh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quadmesh/quadmesh_{{ version }}.tar.gz
  sha256: a121404600b0ba76318bbfdc13532ab2912e44daae0d082c87a5a196616cf2fa

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: datasets, knitr, rmarkdown, palr, rgl, testthat, ncdf4, covr, vdiffr, proj4
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-geometry
    - r-gridbase
    - r-png
    - r-raster
    - r-reproj >=0.2.0
    - r-sp
    - r-viridis

  run:
    - r-base
    - r-geometry
    - r-gridbase
    - r-png
    - r-raster
    - r-reproj >=0.2.0
    - r-sp
    - r-viridis

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('quadmesh')"           # [not win]
    - "\"%R%\" -e \"library('quadmesh')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hypertidy/quadmesh
  license: GPL-3
  summary: Create surface forms from matrix or 'raster' data for flexible plotting and conversion
    to other mesh types. The functions 'quadmesh' or 'triangmesh' produce a continuous
    surface as a 'mesh3d' object as used by the 'rgl' package. This is used for plotting
    raster data in 3D (optionally with texture), and allows the application of a map
    projection without data loss. There are discrete forms of these continuous surfaces
    available with 'dquadmesh' and 'dtriangmesh' functions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: quadmesh
# Type: Package
# Title: Quadrangle Mesh
# Version: 0.3.0
# Authors@R: person("Michael D.","Sumner", role = c("aut", "cre"), email = "mdsumner@gmail.com")
# Description: Create surface forms from matrix or 'raster' data for flexible plotting and conversion to other mesh types. The functions 'quadmesh' or 'triangmesh' produce a continuous surface as a 'mesh3d' object as used by the 'rgl' package. This is used for plotting raster data in 3D (optionally with texture), and allows the application of a map projection without data loss. There are discrete forms of these continuous surfaces available with 'dquadmesh' and 'dtriangmesh' functions.
# License: GPL-3
# LazyData: TRUE
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Encoding: UTF-8
# Imports: raster, gridBase, viridis, png, sp, geometry, reproj (>= 0.2.0)
# Suggests: datasets, knitr, rmarkdown, palr, rgl, testthat, ncdf4, covr, vdiffr, proj4
# URL: https://github.com/hypertidy/quadmesh
# BugReports: https://github.com/hypertidy/quadmesh/issues
# VignetteBuilder: knitr
# ByteCompile: true
# NeedsCompilation: no
# Packaged: 2019-01-16 03:43:12 UTC; michae_sum
# Author: Michael D. Sumner [aut, cre]
# Maintainer: Michael D. Sumner <mdsumner@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-16 06:20:14 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
