{% set version = '0.2.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cpp11
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cpp11_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cpp11/cpp11_{{ version }}.tar.gz
  sha256: 6fef9306c0c3043252c987e77c99ef679b2ea46dffafae318dbeb38ad21a2e20

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bench, brio, callr, cli, covr, decor, desc, ggplot2, glue, knitr, lobstr, mockery, progress, rmarkdown, scales, testthat, tibble, utils, vctrs, withr
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cpp11')"           # [not win]
    - "\"%R%\" -e \"library('cpp11')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/cpp11

  license: MIT
  summary: Provides a header only, C++11 interface to R's C interface.  Compared to other approaches
    'cpp11' strives to be safe against long jumps from the C API as well as C++ exceptions,
    conform to normal R function semantics and supports interaction with 'ALTREP' vectors.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: cpp11
# Title: A C++11 Interface for R's C Interface
# Version: 0.2.5
# Authors@R: c(person(given = "Jim", family = "Hester", role = c("aut", "cre"), email = "jim.hester@rstudio.com", comment = c(ORCID = "0000-0002-2739-7082")), person(given = "Romain", family = "Francois", role = "ctb"), person(given = "Benjamin", family = "Kietzman", role = "ctb"), person(given = "RStudio", role = c("cph", "fnd")))
# Description: Provides a header only, C++11 interface to R's C interface.  Compared to other approaches 'cpp11' strives to be safe against long jumps from the C API as well as C++ exceptions, conform to normal R function semantics and supports interaction with 'ALTREP' vectors.
# License: MIT + file LICENSE
# URL: https://github.com/r-lib/cpp11
# BugReports: https://github.com/r-lib/cpp11/issues
# Suggests: bench, brio, callr, cli, covr, decor, desc, ggplot2, glue, knitr, lobstr, mockery, progress, rmarkdown, scales, testthat, tibble, utils, vctrs, withr
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Config/Needs/cpp11/cpp_register: brio, cli, decor, desc, glue, tibble, vctrs
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# SystemRequirements: C++11
# NeedsCompilation: no
# Packaged: 2021-01-12 19:57:59 UTC; jhester
# Author: Jim Hester [aut, cre] (<https://orcid.org/0000-0002-2739-7082>), Romain Francois [ctb], Benjamin Kietzman [ctb], RStudio [cph, fnd]
# Maintainer: Jim Hester <jim.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2021-01-12 21:20:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
