{% set version = '0.45' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rastervis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rasterVis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rasterVis/rasterVis_{{ version }}.tar.gz
  sha256: 7130fef4b1795ebc13f5ce3a964d70641c14b2ff96dac518a4e8506325122d74

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rgl, ggplot2, colorspace, dichromat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcolorbrewer
    - r-hexbin
    - r-lattice
    - r-latticeextra
    - r-raster >=2.0_12
    - r-sp >=1.0_6
    - r-viridislite
    - r-zoo

  run:
    - r-base
    - r-rcolorbrewer
    - r-hexbin
    - r-lattice
    - r-latticeextra
    - r-raster >=2.0_12
    - r-sp >=1.0_6
    - r-viridislite
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rasterVis')"           # [not win]
    - "\"%R%\" -e \"library('rasterVis')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://oscarperpinan.github.io/rastervis
  license: GPL-3
  summary: Methods for enhanced visualization and interaction with raster data. It implements
    visualization methods for quantitative data and categorical data, both for univariate
    and multivariate rasters. It also provides methods to display spatiotemporal rasters,
    and vector fields. See the website for examples.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: rasterVis
# Type: Package
# Title: Visualization Methods for Raster Data
# Version: 0.45
# Encoding: UTF-8
# Authors@R: c(person("Oscar", "Perpinan Lamigueiro", email="oscar.perpinan@gmail.com", role=c('cre', 'aut'), comment = c(ORCID = "0000-0002-4134-7196")), person("Robert", "Hijmans", email= "r.hijmans@gmail.com", role='aut'))
# Description: Methods for enhanced visualization and interaction with raster data. It implements visualization methods for quantitative data and categorical data, both for univariate and multivariate rasters. It also provides methods to display spatiotemporal rasters, and vector fields. See the website for examples.
# URL: http://oscarperpinan.github.io/rastervis
# BugReports: https://github.com/oscarperpinan/rastervis/issues
# License: GPL-3
# LazyLoad: yes
# Depends: R (>= 2.14.0), methods, raster (>= 2.0-12), lattice, latticeExtra
# Imports: stats, utils, parallel, grid, grDevices, RColorBrewer, hexbin, sp (>= 1.0-6), zoo, viridisLite
# Suggests: rgl, ggplot2, colorspace, dichromat
# NeedsCompilation: no
# Packaged: 2018-06-02 14:44:13 UTC; oscar
# Author: Oscar Perpinan Lamigueiro [cre, aut] (<https://orcid.org/0000-0002-4134-7196>), Robert Hijmans [aut]
# Maintainer: Oscar Perpinan Lamigueiro <oscar.perpinan@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-06-02 22:57:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
