{% set name = "nibabel" %}
{% set version = "3.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 855e0f0795282c0d32ffc25e5d4e1b4b2c7b84d8e385f8959efdc640ea909947

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
    - numpy
    - six
  run:
    - python
    - numpy >=1.14
    - six
    - packaging >=14.3

test:
  imports:
    - nibabel
    - nibabel.benchmarks
    - nibabel.cifti2
    - nibabel.cifti2.tests
    - nibabel.cmdline
    - nibabel.cmdline.tests
    - nibabel.externals
    - nibabel.externals.tests
    - nibabel.freesurfer
    - nibabel.freesurfer.tests
    - nibabel.gifti
    - nibabel.gifti.tests
    - nibabel.nicom
    - nibabel.nicom.tests
    - nibabel.streamlines
    - nibabel.streamlines.tests
    - nibabel.testing
    - nibabel.tests
    - nisext
    - nisext.tests

about:
  home: http://nipy.org/nibabel
  license: MIT
  license_family: MIT
  license_file: 
  summary: Access a multitude of neuroimaging data formats
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - vfonov
