{% set name = "lifelines" %}
{% set version = "0.25.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d8d8ba0c7edd3671e6295501d27e10c1a8e0feb24d4cdc72af8f9c83e2753d4e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - autograd >=1.3
    - autograd-gamma >=0.3
    - matplotlib >=3.0
    - numpy >=1.14.0
    - pandas >=0.23.0
    - patsy >=0.5.0
    - pip
    - python
    - scipy >=1.2.0
  run:
    - autograd >=1.3
    - autograd-gamma >=0.3
    - matplotlib >=3.0
    - numpy >=1.14.0
    - pandas >=0.23.0
    - patsy >=0.5.0
    - python
    - scipy >=1.2.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: "https://github.com/CamDavidsonPilon/lifelines"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
