{% set version = '2.6.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggmap/ggmap_{{ version }}.tar.gz
  sha256: fc450ef422005fc7d2018a34f6b410fbdf80824f9ed60351d91205c413585a57

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, stringr, hexbin, dplyr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rgooglemaps
    - r-digest
    - r-geosphere
    - r-ggplot2 >=2.0.0
    - r-jpeg
    - r-mapproj
    - r-plyr
    - r-png
    - r-proto
    - r-reshape2
    - r-rjson
    - r-scales

  run:
    - r-base
    - r-rgooglemaps
    - r-digest
    - r-geosphere
    - r-ggplot2 >=2.0.0
    - r-jpeg
    - r-mapproj
    - r-plyr
    - r-png
    - r-proto
    - r-reshape2
    - r-rjson
    - r-scales

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ggmap')"           # [not win]
    - "\"%R%\" -e \"library('ggmap')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/dkahle/ggmap
  license: GPL-2
  summary: A collection of functions to visualize spatial data and models on top of static maps
    from various online sources (e.g Google Maps and Stamen Maps). It includes tools
    common to those tasks, including functions for geolocation and routing.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: ggmap
# Version: 2.6.1
# Title: Spatial Visualization with ggplot2
# Description: A collection of functions to visualize spatial data and models on top of static maps from various online sources (e.g Google Maps and Stamen Maps). It includes tools common to those tasks, including functions for geolocation and routing.
# URL: https://github.com/dkahle/ggmap
# BugReports: https://github.com/dkahle/ggmap/issues
# Authors@R: c(person("David", "Kahle", email = "david.kahle@gmail.com", role = c("aut", "cre")), person("Hadley", "Wickham", email = "h.wickham@gmail.com", role = "aut"))
# Depends: R (>= 2.14.0), ggplot2 (>= 2.0.0)
# Imports: proto, RgoogleMaps, png, plyr, reshape2, rjson, mapproj, jpeg, geosphere, digest, scales
# Suggests: MASS, stringr, hexbin, dplyr
# License: GPL-2
# LazyData: true
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-01-22 15:39:39 UTC; david_kahle
# Author: David Kahle [aut, cre], Hadley Wickham [aut]
# Maintainer: David Kahle <david.kahle@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-01-23 00:37:27

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
