{% set version = '2.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-leaflet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/leaflet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/leaflet/leaflet_{{ version }}.tar.gz
  sha256: fa448d20940e01e953e0706fc5064b0fa347e69fa967792599eb03c52b2e3114

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, maps, sf, shiny, testit (>= 0.4), rgdal, rgeos, R6, RJSONIO, purrr, testthat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcolorbrewer
    - r-base64enc
    - r-crosstalk
    - r-htmltools
    - r-htmlwidgets
    - r-magrittr
    - r-markdown
    - r-png
    - r-raster
    - r-scales >=1.0.0
    - r-sp
    - r-viridis >=0.5.1

  run:
    - r-base
    - r-rcolorbrewer
    - r-base64enc
    - r-crosstalk
    - r-htmltools
    - r-htmlwidgets
    - r-magrittr
    - r-markdown
    - r-png
    - r-raster
    - r-scales >=1.0.0
    - r-sp
    - r-viridis >=0.5.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('leaflet')"           # [not win]
    - "\"%R%\" -e \"library('leaflet')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://rstudio.github.io/leaflet/
  license: GPL-3
  summary: Create and customize interactive maps using the 'Leaflet' JavaScript library and the
    'htmlwidgets' package. These maps can be used directly from the R console, from
    'RStudio', in Shiny applications and R Markdown documents.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: leaflet
# Type: Package
# Title: Create Interactive Web Maps with the JavaScript 'Leaflet' Library
# Version: 2.0.2
# Authors@R: c( person("Joe", "Cheng", email = "joe@rstudio.com", role = c("aut", "cre")), person("Bhaskar", "Karambelkar", role = c("aut")), person("Yihui", "Xie", role = c("aut")), person("Hadley", "Wickham", role = c("ctb")), person("Kenton", "Russell", role = c("ctb")), person("Kent", "Johnson", role = c("ctb")), person("Barret", "Schloerke", role = c("ctb")), person("jQuery Foundation and contributors", role = c("ctb", "cph"), comment = "jQuery library"), person("Vladimir", "Agafonkin", role = c("ctb", "cph"), comment = "Leaflet library"), person("CloudMade", role = c("cph"), comment = "Leaflet library"), person("Leaflet contributors", role = c("ctb"), comment = "Leaflet library"), person("Leaflet Providers contributors", role = c("ctb", "cph"), comment = "Leaflet Providers plugin"), person("Brandon Copeland", role = c("ctb", "cph"), comment = "leaflet-measure plugin"), person("Joerg Dietrich", role = c("ctb", "cph"), comment = "Leaflet.Terminator plugin"), person("Benjamin Becquet", role = c("ctb", "cph"), comment = "Leaflet.MagnifyingGlass plugin"), person("Norkart AS", role = c("ctb", "cph"), comment = "Leaflet.MiniMap plugin"), person("L. Voogdt", role = c("ctb", "cph"), comment = "Leaflet.awesome-markers plugin"), person("Daniel Montague", role = c("ctb", "cph"), comment = "Leaflet.EasyButton plugin"), person("Kartena AB", role = c("ctb", "cph"), comment = "Proj4Leaflet plugin"), person("Robert Kajic", role = c("ctb", "cph"), comment = "leaflet-locationfilter plugin"), person("Mapbox", role = c("ctb", "cph"), comment = "leaflet-omnivore plugin"), person("Michael Bostock", role = c("ctb", "cph"), comment = "topojson"), person("RStudio", role = c("cph")) )
# Maintainer: Joe Cheng <joe@rstudio.com>
# Description: Create and customize interactive maps using the 'Leaflet' JavaScript library and the 'htmlwidgets' package. These maps can be used directly from the R console, from 'RStudio', in Shiny applications and R Markdown documents.
# License: GPL-3
# URL: http://rstudio.github.io/leaflet/
# BugReports: https://github.com/rstudio/leaflet/issues
# Depends: R (>= 3.1.0)
# Imports: base64enc, crosstalk, htmlwidgets, htmltools, magrittr, markdown, methods, png, RColorBrewer, raster, scales (>= 1.0.0), sp, stats, viridis (>= 0.5.1)
# Suggests: knitr, maps, sf, shiny, testit (>= 0.4), rgdal, rgeos, R6, RJSONIO, purrr, testthat
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# LazyData: true
# NeedsCompilation: no
# Packaged: 2018-08-24 20:03:55 UTC; barret
# Author: Joe Cheng [aut, cre], Bhaskar Karambelkar [aut], Yihui Xie [aut], Hadley Wickham [ctb], Kenton Russell [ctb], Kent Johnson [ctb], Barret Schloerke [ctb], jQuery Foundation and contributors [ctb, cph] (jQuery library), Vladimir Agafonkin [ctb, cph] (Leaflet library), CloudMade [cph] (Leaflet library), Leaflet contributors [ctb] (Leaflet library), Leaflet Providers contributors [ctb, cph] (Leaflet Providers plugin), Brandon Copeland [ctb, cph] (leaflet-measure plugin), Joerg Dietrich [ctb, cph] (Leaflet.Terminator plugin), Benjamin Becquet [ctb, cph] (Leaflet.MagnifyingGlass plugin), Norkart AS [ctb, cph] (Leaflet.MiniMap plugin), L. Voogdt [ctb, cph] (Leaflet.awesome-markers plugin), Daniel Montague [ctb, cph] (Leaflet.EasyButton plugin), Kartena AB [ctb, cph] (Proj4Leaflet plugin), Robert Kajic [ctb, cph] (leaflet-locationfilter plugin), Mapbox [ctb, cph] (leaflet-omnivore plugin), Michael Bostock [ctb, cph] (topojson), RStudio [cph]
# Repository: CRAN
# Date/Publication: 2018-08-27 14:12:16 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
