package:
  name: minc-toolkit-v2
  version: "1.9.17"

source:
  url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.17-test/minc-toolkit-v2-551800bf11df8d5e5728e5e91cf41c3a5cc8ef4b.tar.gz
  sha1: 6e76fe2797d0900af5886539ef992c36a79fb95c

requirements:
  build:
    - cmake
    - flex
    - bison
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - {{ compiler('fortran') }}  [linux]
    - perl
    - system                     [linux]
    - openblas=0.2.20
  run:
    - perl
    - openblas

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2
  