package:
  name: minc-toolkit-v2
  version: "1.9.18"

source:
  url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18.1/minc-toolkit-v2-1.9.18.1.tar.xz
  sha256: eda5424f1046dcf39e87b75e8d207edf381318af30228a655ec1c704f4fc8699
  #git_url: https://github.com/BIC-MNI/minc-toolkit-v2.git
  #git_rev: develop-1.9.18
  #path: /Users/vfonov/src/minc-toolkit-v2

requirements:
  build:
    - cmake
    - make
    - flex
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - openblas            # [minctoolkit_variant == 'openblas'] 
    - hdf5       {{hdf5}}
    - pcre
    - libnetcdf  {{libnetcdf}}
    - zlib
    - gsl
    - fftw
    - jpeg
    - openjpeg
    - perl
    - expat
  host:
    - perl
    - zlib
  run:
    - perl
    - hdf5      
    - libnetcdf 
    - zlib
    - gsl
    - jpeg
    - fftw
    - jpeg
    - openjpeg
    - expat
    - pcre
  

test:
  commands:
    - minccalc -version
    - antsRegistration --version # [minctoolkit_variant != 'lite'] 

build:
  number: 9
  string: {{ minctoolkit_variant }}_h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_compatible('hdf5', max_pin='x.x') }}
    - {{ pin_compatible('libnetcdf', max_pin='x.x') }}
    - {{ pin_compatible('fftw', max_pin='x.x') }}
    - openjpeg
    - zlib
    - {{ pin_compatible('gsl', max_pin='x.x') }}
    - jpeg
    - expat

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans (external libraries)'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2
