package:
  name: minc-toolkit-v2
  version: "1.9.17"

source:
  #url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.17-test/minc-toolkit-v2-1.9.17.tar.xz
  #sha256: 0b4e8b5a134c44d2054cba71fd0e005136ee9b018cf4984acb467d5c0708fd7d
  path: /home/vfonov/src/minc-toolkit-v2

requirements:
  build:
    - cmake
    - make
    - flex
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - system                     # [linux]
    - openblas =0.3.3            # [minctoolkit_variant == 'openblas'] 
    - hdf5 <=1.8.18
    - pcre
    - libnetcdf <=4.5.0
    - zlib
    - gsl
    - fftw
    - jpeg =9b
    - openjpeg
    - perl
    - expat
  host:
    - perl
    - zlib
  run:
    - perl
    - openblas =0.3.3        # [minctoolkit_variant == 'openblas'] 
    - hdf5 <=1.8.18
    - pcre
    - libnetcdf <=4.5.0
    - zlib
    - gsl
    - fftw
    - jpeg=9b
    - openjpeg
    - expat                 # [minctoolkit_variant != 'lite'] 
    - flex

test:
  commands:
    - minccalc -version
    - antsRegistration --version #[minctoolkit_variant != 'lite'] 

build:
  number: 8
  string: {{ minctoolkit_variant }}_h{{PKG_HASH}}_{{ PKG_BUILDNUM }}

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans (external libraries)'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2

