package:
  name: minc-toolkit-v2
  version: "1.9.18"

source:
  url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18-test/minc-toolkit-v2-1e0ebb8e657e69e97777d4ef8d06880f8e219976.tar.xz
  sha256: d705dcf860a4bf8566f0bf61b2101ab79ea58b0055839021adf03b7fda44e589
  #path: /home/vfonov/src/minc-toolkit-v2

requirements:
  build:
    - cmake
    - make
    - flex
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - system                     # [linux]
    - openblas =0.3.3            # [minctoolkit_variant == 'openblas'] 
    - hdf5 ==1.10.4
    - pcre
    - libnetcdf ==4.6.1
    - zlib
    - gsl
    - fftw
    - jpeg =9b
    - openjpeg
    - perl
    - expat
  host:
    - perl
    - zlib
  run:
    - perl
    - openblas =0.3.3        # [minctoolkit_variant == 'openblas'] 
    - hdf5 ==1.10.4
    - pcre
    - libnetcdf  ==4.6.1
    - zlib
    - gsl
    - fftw
    - jpeg=9b
    - openjpeg
    - expat                 # [minctoolkit_variant != 'lite'] 
    - flex

test:
  commands:
    - minccalc -version
    - antsRegistration --version #[minctoolkit_variant != 'lite'] 

build:
  number: 0
  string: {{ minctoolkit_variant }}_h{{PKG_HASH}}_{{ PKG_BUILDNUM }}

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans (external libraries)'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2
