package:
  name: minc-toolkit-v2
  version: "1.9.18"

source:
  url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18/minc-toolkit-v2-1.9.18.tar.xz
  sha256: 4295561bfcfb8778287df24358e001a6c029ef964799aa279840dd5b117eebd8
  #git_url: https://github.com/BIC-MNI/minc-toolkit-v2.git
  #git_rev: develop-1.9.18
  #path: /Users/vfonov/src/minc-toolkit-v2

requirements:
  build:
    - cmake
    - make
    - flex
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - openblas            # [minctoolkit_variant == 'openblas'] 
    - hdf5 
    - pcre
    - libnetcdf 
    - zlib
    - gsl
    - fftw
    - jpeg
    - openjpeg
    - perl
    - expat
  host:
    - perl
    - zlib
  run:
    - perl
    - hdf5 

test:
  commands:
    - minccalc -version
    - antsRegistration --version # [minctoolkit_variant != 'lite'] 

build:
  number: 5
  string: {{ minctoolkit_variant }}_h{{PKG_HASH}}_{{ PKG_BUILDNUM }}

about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans (external libraries)'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2
