package:
  name: minc-toolkit-v2
  version: "1.9.17"

source:
  url: https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.17-test/minc-toolkit-v2-2a5d2eac21e82c8ba36c2b6e4fa01e3b0e831668.tar.gz
  sha256: c602bd3a7be3d055b4de2388484f2479ae8f9939bc205d4b82f7c8952c9397d9

requirements:
  build:
    - cmake
    - flex
    - bison
    - {{ compiler('c') }}        [linux]
    - {{ compiler('cxx') }}      [linux]
    - {{ compiler('fortran') }}  [linux]
    - system                     [linux]
    - openblas =0.2.20
    - hdf5 <=1.8.18
    - pcre
    - libnetcdf <=4.5.0
    - zlib
    - gsl
    - fftw
    - jpeg=9b
    - openjpeg
    - perl
    - expat
  run:
    - perl
    - openblas
    - openblas =0.2.20
    - hdf5 <=1.8.18
    - pcre
    - libnetcdf <=4.5.0
    - zlib
    - gsl
    - fftw
    - jpeg=9b
    - openjpeg
    - expat

build:
  number: 0


about:
  home: http://bic-mni.github.io/
  license: GPL3
  summary: 'Toolkit for processing MRI scans (external libraries)'
  description: |
    This metaproject bundles multiple MINC-based packages that historically have been developed somewhat independently.
  doc_url: http://bic-mni.github.io/man-pages
  dev_url: https://github.com/BIC-MNI/minc-toolkit-v2
  