{% set version = '0.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapdeck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapdeck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapdeck/mapdeck_{{ version }}.tar.gz
  sha256: 9376cb4590b91c7931b0f2194882213688f2f5e20a7b703e1b39e2c3b32792ea

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, jsonlite, knitr, rmarkdown, sf, spatialwidget, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-colourvalues >=0.2.2
    - r-geojsonsf >=1.3.0
    - r-googlepolylines >=0.7.2
    - r-htmltools
    - r-htmlwidgets
    - r-jsonify >=0.2.0
    - r-magrittr
    - r-rapidjsonr
    - r-shiny
    - r-spatialwidget >=0.2.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rcpp
    - r-colourvalues >=0.2.2
    - r-geojsonsf >=1.3.0
    - r-googlepolylines >=0.7.2
    - r-htmltools
    - r-htmlwidgets
    - r-jsonify >=0.2.0
    - r-magrittr
    - r-rapidjsonr
    - r-shiny
    - r-spatialwidget >=0.2.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mapdeck')"           # [not win]
    - "\"%R%\" -e \"library('mapdeck')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://symbolixau.github.io/mapdeck/articles/mapdeck.html
  license: GPL-3
  summary: Provides a mechanism to plot an interactive map using 'Mapbox GL'  (<https://www.mapbox.com/mapbox-gl-js/api/>),
    a javascript library for interactive maps, and 'Deck.gl' (<http://deck.gl/#/>),
    a javascript library which uses 'WebGL' for  visualising large data sets.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: mapdeck
# Type: Package
# Title: Interactive Maps Using 'Mapbox GL JS' and 'Deck.gl'
# Version: 0.2.1
# Date: 2019-01-22
# Authors@R: c( person("David", "Cooley", ,"dcooley@symbolix.com.au", role = c("aut", "cre")) )
# Description: Provides a mechanism to plot an interactive map using 'Mapbox GL'  (<https://www.mapbox.com/mapbox-gl-js/api/>), a javascript library for interactive maps, and 'Deck.gl' (<http://deck.gl/#/>), a javascript library which uses 'WebGL' for  visualising large data sets.
# License: GPL-3
# URL: https://symbolixau.github.io/mapdeck/articles/mapdeck.html
# BugReports: https://github.com/SymbolixAU/mapdeck/issues
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.3.0)
# Imports: colourvalues (>= 0.2.2), geojsonsf (>= 1.3.0), googlePolylines (>= 0.7.2), htmltools, htmlwidgets, jsonify (>= 0.2.0), magrittr, Rcpp, shiny
# RoxygenNote: 6.1.1
# Suggests: covr, jsonlite, knitr, rmarkdown, sf, spatialwidget, testthat
# VignetteBuilder: knitr
# LinkingTo: BH, colourvalues, geojsonsf, jsonify, rapidjsonr, Rcpp, spatialwidget (>= 0.2.0)
# NeedsCompilation: yes
# Packaged: 2019-01-22 03:58:14 UTC; david
# Author: David Cooley [aut, cre]
# Maintainer: David Cooley <dcooley@symbolix.com.au>
# Repository: CRAN
# Date/Publication: 2019-01-22 09:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
