{% set version = '2.0-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmaptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmaptools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmaptools/tmaptools_{{ version }}.tar.gz
  sha256: 9febf4dc5128ddc977bdecfb0c3dd32e99f280b0aec5787f3fab76720716d27d

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: tmap (>= 2.0), rmapshaper, osmdata, OpenStreetMap, png, shiny, shinyjs
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-kernsmooth
    - r-rcolorbrewer
    - r-xml
    - r-classint
    - r-dichromat
    - r-lwgeom >=0.1_4
    - r-magrittr
    - r-raster >=2.5_2
    - r-rgdal
    - r-rgeos
    - r-sf >=0.6_0
    - r-sp
    - r-units >=0.5_1
    - r-viridislite
    - r-codetools

  run:
    - r-base
    - r-kernsmooth
    - r-rcolorbrewer
    - r-xml
    - r-classint
    - r-dichromat
    - r-lwgeom >=0.1_4
    - r-magrittr
    - r-raster >=2.5_2
    - r-rgdal
    - r-rgeos
    - r-sf >=0.6_0
    - r-sp
    - r-units >=0.5_1
    - r-viridislite
    - r-codetools

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tmaptools')"           # [not win]
    - "\"%R%\" -e \"library('tmaptools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/mtennekes/tmaptools
  license: GPL-3
  summary: Set of tools for reading and processing spatial data. The aim is to supply the workflow
    to create thematic maps. This package also facilitates 'tmap', the package for visualizing
    thematic maps.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: tmaptools
# Type: Package
# Title: Thematic Map Tools
# Version: 2.0-1
# Authors@R: person("Martijn", "Tennekes", email = "mtennekes@gmail.com", role = c("aut", "cre"))
# Description: Set of tools for reading and processing spatial data. The aim is to supply the workflow to create thematic maps. This package also facilitates 'tmap', the package for visualizing thematic maps.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Date: 2018-08-06
# Depends: R (>= 3.0), methods
# Imports: sp, sf (>= 0.6-0), lwgeom (>= 0.1-4), units (>= 0.5-1), grid, raster (>= 2.5-2), rgdal, rgeos, classInt, KernSmooth, magrittr, RColorBrewer, viridisLite, stats, dichromat, XML
# Suggests: tmap (>= 2.0), rmapshaper, osmdata, OpenStreetMap, png, shiny, shinyjs
# URL: https://github.com/mtennekes/tmaptools
# BugReports: https://github.com/mtennekes/tmaptools/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-08-07 07:59:16 UTC; mtes
# Author: Martijn Tennekes [aut, cre]
# Maintainer: Martijn Tennekes <mtennekes@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-08-07 08:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
