{% set version = '0.0.9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-osmdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/osmdata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/osmdata/osmdata_{{ version }}.tar.gz
  sha256: 8c5bdd676857b505f8f3b4ec31f68fe10cdc89323752782429049d7a137c7afe

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: devtools, knitr, rmarkdown, roxygen2, sf, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.12.4
    - r-curl
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-rvest
    - r-sp
    - r-tibble
    - r-xml2

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.4
    - r-curl
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-rvest
    - r-sp
    - r-tibble
    - r-xml2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('osmdata')"           # [not win]
    - "\"%R%\" -e \"library('osmdata')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/osmdata
  license: GPL-3
  summary: Download and import of 'OpenStreetMap' ('OSM') data as 'sf' or 'sp' objects.  'OSM'
    data are extracted from the 'Overpass' web server and processed with very fast 'C++'
    routines for return to 'R'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: osmdata
# Version: 0.0.9
# Authors@R: c( person("Mark", "Padgham", email="mark.padgham@email.com", role=c("aut", "cre")), person("Bob", "Rudis", role="aut"), person("Robin", "Lovelace", role="aut"),  person("Maelle", "Salmon", role="aut"), person("Andrew", "Smith", role="ctb"), person("James", "Smith", role="ctb"), person("Marcin", "Kalicinski", role=c("ctb", "cph"), comment="Author of included RapidXML code"), person("Finkelstein", "Noam", role=c("ctb","cph"), comment="Author of included stub.R code"), person ("Bartnik", "Lukasz", role=c("ctb","cph"), comment="Author of included stub.R code"))
# Maintainer: Mark Padgham <mark.padgham@email.com>
# Title: Import 'OpenStreetMap' Data as Simple Features or Spatial Objects
# Description: Download and import of 'OpenStreetMap' ('OSM') data as 'sf' or 'sp' objects.  'OSM' data are extracted from the 'Overpass' web server and processed with very fast 'C++' routines for return to 'R'.
# Depends: R (>= 3.2.4)
# License: GPL-3
# SystemRequirements: C++11
# NeedsCompilation: yes
# LazyData: true
# Imports: curl, httr, lubridate, magrittr, methods, Rcpp (>= 0.12.4), rvest, jsonlite, sp, tibble, utils, xml2
# Suggests: devtools, knitr, rmarkdown, roxygen2, sf, testthat
# LinkingTo: Rcpp
# URL: https://github.com/ropensci/osmdata
# BugReports: https://github.com/ropensci/osmdata/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# X-schema.org-applicationCategory: Data Access
# X-schema.org-keywords: open0street0map, openstreetmap, overpass0API, OSM
# X-schema.org-isPartOf: https://ropensci.org
# Packaged: 2018-12-14 11:12:50 UTC; markus
# Author: Mark Padgham [aut, cre], Bob Rudis [aut], Robin Lovelace [aut], Maelle Salmon [aut], Andrew Smith [ctb], James Smith [ctb], Marcin Kalicinski [ctb, cph] (Author of included RapidXML code), Finkelstein Noam [ctb, cph] (Author of included stub.R code), Bartnik Lukasz [ctb, cph] (Author of included stub.R code)
# Repository: CRAN
# Date/Publication: 2018-12-19 08:13:28 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
