{% set version = '1.12.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.table
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/data.table_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/data.table/data.table_{{ version }}.tar.gz
  sha256: d3a75f3a355ff144cc20a476041617e21fcf2a9f79265fd9bbd4693f3671f9dc

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, curl, R.utils, knitr, xts, nanotime, zoo, yaml
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('data.table')"           # [not win]
    - "\"%R%\" -e \"library('data.table')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://r-datatable.com, https://Rdatatable.gitlab.io/data.table, https://github.com/Rdatatable/data.table
  license: MPL-2.0 | file LICENSE
  summary: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete
    of columns by group using no copies at all, list columns, friendly and fast character-separated-value
    read/write. Offers a natural and flexible syntax, for faster development.
  license_family: OTHER
  license_file:
    - LICENSE

# The original CRAN metadata for this package was:

# Package: data.table
# Version: 1.12.8
# Title: Extension of `data.frame`
# Authors@R: c( person("Matt","Dowle",           role=c("aut","cre"), email="mattjdowle@gmail.com"), person("Arun","Srinivasan",      role="aut",          email="arunkumar.sriniv@gmail.com"), person("Jan","Gorecki",          role="ctb"), person("Michael","Chirico",      role="ctb"), person("Pasha","Stetsenko",      role="ctb"), person("Tom","Short",            role="ctb"), person("Steve","Lianoglou",      role="ctb"), person("Eduard","Antonyan",      role="ctb"), person("Markus","Bonsch",        role="ctb"), person("Hugh","Parsonage",       role="ctb"), person("Scott","Ritchie",        role="ctb"), person("Kun","Ren",              role="ctb"), person("Xianying","Tan",         role="ctb"), person("Rick","Saporta",         role="ctb"), person("Otto","Seiskari",        role="ctb"), person("Xianghui","Dong",        role="ctb"), person("Michel","Lang",          role="ctb"), person("Watal","Iwasaki",        role="ctb"), person("Seth","Wenchel",         role="ctb"), person("Karl","Broman",          role="ctb"), person("Tobias","Schmidt",       role="ctb"), person("David","Arenburg",       role="ctb"), person("Ethan","Smith",          role="ctb"), person("Francois","Cocquemas",   role="ctb"), person("Matthieu","Gomez",       role="ctb"), person("Philippe","Chataignon",  role="ctb"), person("Declan","Groves",        role="ctb"), person("Daniel","Possenriede",   role="ctb"), person("Felipe","Parages",       role="ctb"), person("Denes","Toth",           role="ctb"), person("Mus","Yaramaz-David",    role="ctb"), person("Ayappan","Perumal",      role="ctb"), person("James","Sams",           role="ctb"), person("Martin","Morgan",        role="ctb"), person("Michael","Quinn",        role="ctb"), person("@javrucebo","",          role="ctb"), person("@marc-outins","",        role="ctb"), person("Roy","Storey",           role="ctb"), person("Manish","Saraswat",      role="ctb"), person("Morgan","Jacob",         role="ctb"), person("Michael","Schubmehl",    role="ctb"), person("Davis","Vaughan",        role="ctb"))
# Depends: R (>= 3.1.0)
# Imports: methods
# Suggests: bit64, curl, R.utils, knitr, xts, nanotime, zoo, yaml
# SystemRequirements: zlib
# Description: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete of columns by group using no copies at all, list columns, friendly and fast character-separated-value read/write. Offers a natural and flexible syntax, for faster development.
# License: MPL-2.0 | file LICENSE
# URL: http://r-datatable.com, https://Rdatatable.gitlab.io/data.table, https://github.com/Rdatatable/data.table
# BugReports: https://github.com/Rdatatable/data.table/issues
# VignetteBuilder: knitr
# ByteCompile: TRUE
# NeedsCompilation: yes
# Packaged: 2019-12-08 22:28:25.859 UTC; mdowle
# Author: Matt Dowle [aut, cre], Arun Srinivasan [aut], Jan Gorecki [ctb], Michael Chirico [ctb], Pasha Stetsenko [ctb], Tom Short [ctb], Steve Lianoglou [ctb], Eduard Antonyan [ctb], Markus Bonsch [ctb], Hugh Parsonage [ctb], Scott Ritchie [ctb], Kun Ren [ctb], Xianying Tan [ctb], Rick Saporta [ctb], Otto Seiskari [ctb], Xianghui Dong [ctb], Michel Lang [ctb], Watal Iwasaki [ctb], Seth Wenchel [ctb], Karl Broman [ctb], Tobias Schmidt [ctb], David Arenburg [ctb], Ethan Smith [ctb], Francois Cocquemas [ctb], Matthieu Gomez [ctb], Philippe Chataignon [ctb], Declan Groves [ctb], Daniel Possenriede [ctb], Felipe Parages [ctb], Denes Toth [ctb], Mus Yaramaz-David [ctb], Ayappan Perumal [ctb], James Sams [ctb], Martin Morgan [ctb], Michael Quinn [ctb], @javrucebo [ctb], @marc-outins [ctb], Roy Storey [ctb], Manish Saraswat [ctb], Morgan Jacob [ctb], Michael Schubmehl [ctb], Davis Vaughan [ctb]
# Maintainer: Matt Dowle <mattjdowle@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-12-09 10:30:10 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
