{% set version = '0.8.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggrepel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggrepel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggrepel/ggrepel_{{ version }}.tar.gz
  sha256: 6386606e716d326354a29fcb6cd09f9b3d3b5e7c5ba0d5f7ff35416b1a4177d4

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat, gridExtra, devtools, prettydoc
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-ggplot2 >=2.2.0
    - r-scales >=0.3.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-ggplot2 >=2.2.0
    - r-scales >=0.3.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ggrepel')"           # [not win]
    - "\"%R%\" -e \"library('ggrepel')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/slowkow/ggrepel
  license: GPL-3 | file LICENSE
  summary: Provides text and label geoms for 'ggplot2' that help to avoid overlapping text labels.
    Labels repel away from each other and away from the data points.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: ggrepel
# Version: 0.8.0
# Authors@R: c( person("Kamil", "Slowikowski", email = "kslowikowski@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-2843-6370")), person("Alicia", "Schep", role = "ctb", comment = c(ORCID = "0000-0002-3915-0618")), person("Sean", "Hughes", role = "ctb"), person("Saulius", "Lukauskas", role = "ctb"), person("Jean-Olivier", "Irisson", role = "ctb", comment = c(ORCID = "0000-0003-4920-3880")), person("Zhian N", "Kamvar", role = "ctb", comment = c(ORCID = "0000-0003-1458-7108")), person("Thompson", "Ryan", role = "ctb", comment = c(ORCID = "0000-0002-0450-8181")), person("Dervieux", "Christophe", role = "ctb", comment = c(ORCID = "0000-0003-4474-2498")), person("Yutani", "Hiroaki", role = "ctb"), person("Pierre", "Gramme", role = "ctb") )
# Title: Automatically Position Non-Overlapping Text Labels with 'ggplot2'
# Description: Provides text and label geoms for 'ggplot2' that help to avoid overlapping text labels. Labels repel away from each other and away from the data points.
# Depends: R (>= 3.0.0), ggplot2 (>= 2.2.0)
# Imports: grid, Rcpp, scales (>= 0.3.0)
# Suggests: knitr, rmarkdown, testthat, gridExtra, devtools, prettydoc
# VignetteBuilder: knitr
# License: GPL-3 | file LICENSE
# URL: http://github.com/slowkow/ggrepel
# BugReports: http://github.com/slowkow/ggrepel/issues
# RoxygenNote: 6.0.1
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2018-05-09 13:53:18 UTC; slowikow
# Author: Kamil Slowikowski [aut, cre] (<https://orcid.org/0000-0002-2843-6370>), Alicia Schep [ctb] (<https://orcid.org/0000-0002-3915-0618>), Sean Hughes [ctb], Saulius Lukauskas [ctb], Jean-Olivier Irisson [ctb] (<https://orcid.org/0000-0003-4920-3880>), Zhian N Kamvar [ctb] (<https://orcid.org/0000-0003-1458-7108>), Thompson Ryan [ctb] (<https://orcid.org/0000-0002-0450-8181>), Dervieux Christophe [ctb] (<https://orcid.org/0000-0003-4474-2498>), Yutani Hiroaki [ctb], Pierre Gramme [ctb]
# Maintainer: Kamil Slowikowski <kslowikowski@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-09 15:30:45 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
