{% set version = '2.2-7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cmprsk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cmprsk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cmprsk/cmprsk_{{ version }}.tar.gz
  sha256: 952da4a0fd55a039f64f619c2c7cc29ba2490985ca67d2853de511692f1fb9c6

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-survival

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cmprsk')"           # [not win]
    - "\"%R%\" -e \"library('cmprsk')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.r-project.org
  license: GPL (>= 2)
  summary: Estimation, testing and regression modeling of subdistribution functions in competing
    risks, as described in Gray (1988), A class of K-sample tests for comparing the
    cumulative incidence of a competing risk, Ann. Stat. 16:1141-1154, and Fine JP and
    Gray RJ (1999), A proportional hazards model for the subdistribution of a competing
    risk, JASA, 94:496-509.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: cmprsk
# Version: 2.2-7
# Date: 2014-jun-17
# Title: Subdistribution Analysis of Competing Risks
# Author: Bob Gray <gray@jimmy.harvard.edu>
# Maintainer: Bob Gray <gray@jimmy.harvard.edu>
# Depends: R (>= 2.15.0), survival
# Description: Estimation, testing and regression modeling of subdistribution functions in competing risks, as described in Gray (1988), A class of K-sample tests for comparing the cumulative incidence of a competing risk, Ann. Stat. 16:1141-1154, and Fine JP and Gray RJ (1999), A proportional hazards model for the subdistribution of a competing risk, JASA, 94:496-509.
# License: GPL (>= 2)
# URL: http://www.r-project.org
# Packaged: 2014-06-17 18:45:38 UTC; gray
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-06-17 23:16:43

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
