{% set version = "4.13" %}
# adopted from https://github.com/conda-forge/cgal-feedstock
# split cgal into cgal and cgal-swig


package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.tar.xz
  sha256: 3e3dd7a64febda58be54c3cbeba329ab6a73b72d4d7647ba4931ecd1fad0e3bc

build:
  number: 1
  # mpfr only supports vc14

requirements:
  build:
    - cmake
    - eigen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - mpfr
  run:
    - boost-cpp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

