package:
  name: flann
  version: "1.9.1"

source:
  url: https://github.com/mariusmuja/flann/archive/1.9.1.tar.gz
  sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3

requirements:
  build:
    - cmake=3.9.4
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
    - python
  host:
    - python
    - numpy
    - setuptools
  run: 
    - python
    - {{ pin_compatible('numpy') }}

build:
  number: 0

about:
  home: https://www.cs.ubc.ca/research/flann/
  license: BSD
  summary: 'Fast Library for Approximate Nearest Neighbors'
  description: |
    FLANN is a library for performing fast approximate nearest neighbor searches in high dimensional spaces. It contains a collection of algorithms we found to work best for nearest neighbor search and a system for automatically choosing the best algorithm and optimum parameters depending on the dataset.
