{% set version = '2.17.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr/mlr_{{ version }}.tar.gz
  sha256: ce8bb1c890821b951cb84a50697fc11e39d5fe79198f00380ceea207f77bf274

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: ada, adabag, bartMachine, batchtools, brnn, bst, C50, care, caret (>= 6.0-57), class, classiFunc, clue, cluster, ClusterR, clusterSim (>= 0.44-5), clValid, cmaes, cowplot, CoxBoost, crs, Cubist, deepnet, DiceKriging, DiscriMiner, e1071, earth, elasticnet, emoa, evtree, extraTrees, fda.usc, FDboost, flare, FNN, forecast (>= 8.3), fpc, frbs, FSelector, FSelectorRcpp (>= 0.2.1), gbm, GenSA, ggpubr, glmnet, GPfit, h2o (>= 3.6.0.8), Hmisc, hrbrthemes, irace (>= 2.0), kernlab, kknn, klaR, knitr, laGP, LiblineaR, lintr (>= 1.0.0.9001), MASS, mboost, mco, mda, memoise, mlbench, mldr, mlrMBO, mmpf, modeltools, mRMRe, neuralnet, nnet, nodeHarvest (>= 0.7-3), numDeriv, pamr, pander, party, penalized (>= 0.9-47), pls, PMCMR (>= 4.1), praznik (>= 5.0.0), randomForest, randomForestSRC (>= 2.7.0), ranger (>= 0.8.0), rappdirs, refund, rex, rFerns, rgenoud, rknn, rmarkdown, ROCR, rotationForest, rpart, RRF, rrlda, rsm, RSNNS, rucrdtw, RWeka, sda, sf, smoof, sparseLDA, stepPlr, survAUC, svglite, SwarmSVM, testthat, tgp, TH.data, tsfeatures, vdiffr, wavelets, xgboost (>= 0.7)
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bbmisc >=1.11
    - r-paramhelpers >=1.10
    - r-xml
    - r-backports >=1.1.0
    - r-checkmate >=1.8.2
    - r-data.table >=1.12.4
    - r-ggplot2
    - r-parallelmap >=1.3
    - r-stringi
    - r-survival

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bbmisc >=1.11
    - r-paramhelpers >=1.10
    - r-xml
    - r-backports >=1.1.0
    - r-checkmate >=1.8.2
    - r-data.table >=1.12.4
    - r-ggplot2
    - r-parallelmap >=1.3
    - r-stringi
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mlr')"           # [not win]
    - "\"%R%\" -e \"library('mlr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://mlr.mlr-org.com, https://github.com/mlr-org/mlr
  license: BSD_2_clause
  summary: Interface to a large number of classification and regression techniques, including
    machine-readable parameter descriptions. There is also an experimental extension
    for survival analysis, clustering and general, example-specific cost-sensitive learning.
    Generic resampling, including cross-validation, bootstrapping and subsampling. Hyperparameter
    tuning with modern optimization techniques, for single- and multi-objective problems.
    Filter and wrapper methods for feature selection. Extension of basic learners with
    additional operations common in machine learning, also allowing for easy nested
    resampling. Most operations can be parallelized.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: mlr
# Title: Machine Learning in R
# Version: 2.17.0
# Authors@R: c(person(given = "Bernd", family = "Bischl", role = "aut", email = "bernd_bischl@gmx.net", comment = c(ORCID = "0000-0001-6002-6980")), person(given = "Michel", family = "Lang", role = "aut", email = "michellang@gmail.com", comment = c(ORCID = "0000-0001-9754-0393")), person(given = "Lars", family = "Kotthoff", role = "aut", email = "larsko@uwyo.edu"), person(given = "Julia", family = "Schiffner", role = "aut", email = "schiffner@math.uni-duesseldorf.de"), person(given = "Jakob", family = "Richter", role = "aut", email = "code@jakob-r.de"), person(given = "Zachary", family = "Jones", role = "aut", email = "zmj@zmjones.com"), person(given = "Giuseppe", family = "Casalicchio", role = "aut", email = "giuseppe.casalicchio@stat.uni-muenchen.de", comment = c(ORCID = "0000-0001-5324-5966")), person(given = "Mason", family = "Gallo", role = "aut", email = "masonagallo@gmail.com"), person(given = "Patrick", family = "Schratz", role = c("aut", "cre"), email = "patrick.schratz@gmail.com", comment = c(ORCID = "0000-0003-0748-6624")), person(given = "Jakob", family = "Bossek", role = "ctb", email = "jakob.bossek@tu-dortmund.de", comment = c(ORCID = "0000-0002-4121-4668")), person(given = "Erich", family = "Studerus", role = "ctb", email = "erich.studerus@upkbs.ch", comment = c(ORCID = "0000-0003-4233-0182")), person(given = "Leonard", family = "Judt", role = "ctb", email = "leonard.judt@tu-dortmund.de"), person(given = "Tobias", family = "Kuehn", role = "ctb", email = "tobi.kuehn@gmx.de"), person(given = "Pascal", family = "Kerschke", role = "ctb", email = "kerschke@uni-muenster.de", comment = c(ORCID = "0000-0003-2862-1418")), person(given = "Florian", family = "Fendt", role = "ctb", email = "flo_fendt@gmx.de"), person(given = "Philipp", family = "Probst", role = "ctb", email = "philipp_probst@gmx.de", comment = c(ORCID = "0000-0001-8402-6790")), person(given = "Xudong", family = "Sun", role = "ctb", email = "xudong.sun@stat.uni-muenchen.de", comment = c(ORCID = "0000-0003-3269-2307")), person(given = "Janek", family = "Thomas", role = "ctb", email = "janek.thomas@stat.uni-muenchen.de", comment = c(ORCID = "0000-0003-4511-6245")), person(given = "Bruno", family = "Vieira", role = "ctb", email = "bruno.hebling.vieira@usp.br"), person(given = "Laura", family = "Beggel", role = "ctb", email = "laura.beggel@web.de", comment = c(ORCID = "0000-0002-8872-8535")), person(given = "Quay", family = "Au", role = "ctb", email = "quay.au@stat.uni-muenchen.de", comment = c(ORCID = "0000-0002-5252-8902")), person(given = "Martin", family = "Binder", role = "ctb", email = "ma.binder@campus.lmu.de"), person(given = "Florian", family = "Pfisterer", role = "ctb", email = "pfistererf@googlemail.com"), person(given = "Stefan", family = "Coors", role = "ctb", email = "stefan.coors@gmx.net"), person(given = "Steve", family = "Bronder", role = "ctb", email = "sab2287@columbia.edu"), person(given = "Alexander", family = "Engelhardt", role = "ctb", email = "alexander.w.engelhardt@gmail.com"), person(given = "Christoph", family = "Molnar", role = "ctb", email = "christoph.molnar@stat.uni-muenchen.de"), person(given = "Annette", family = "Spooner", role = "ctb", email = "a.spooner@unsw.edu.au"))
# Description: Interface to a large number of classification and regression techniques, including machine-readable parameter descriptions. There is also an experimental extension for survival analysis, clustering and general, example-specific cost-sensitive learning. Generic resampling, including cross-validation, bootstrapping and subsampling. Hyperparameter tuning with modern optimization techniques, for single- and multi-objective problems. Filter and wrapper methods for feature selection. Extension of basic learners with additional operations common in machine learning, also allowing for easy nested resampling. Most operations can be parallelized.
# License: BSD_2_clause + file LICENSE
# URL: https://mlr.mlr-org.com, https://github.com/mlr-org/mlr
# BugReports: https://github.com/mlr-org/mlr/issues
# Depends: ParamHelpers (>= 1.10), R (>= 3.0.2)
# Imports: backports (>= 1.1.0), BBmisc (>= 1.11), checkmate (>= 1.8.2), data.table (>= 1.12.4), ggplot2, methods, parallelMap (>= 1.3), stats, stringi, survival, utils, XML
# Suggests: ada, adabag, bartMachine, batchtools, brnn, bst, C50, care, caret (>= 6.0-57), class, classiFunc, clue, cluster, ClusterR, clusterSim (>= 0.44-5), clValid, cmaes, cowplot, CoxBoost, crs, Cubist, deepnet, DiceKriging, DiscriMiner, e1071, earth, elasticnet, emoa, evtree, extraTrees, fda.usc, FDboost, flare, FNN, forecast (>= 8.3), fpc, frbs, FSelector, FSelectorRcpp (>= 0.2.1), gbm, GenSA, ggpubr, glmnet, GPfit, h2o (>= 3.6.0.8), Hmisc, hrbrthemes, irace (>= 2.0), kernlab, kknn, klaR, knitr, laGP, LiblineaR, lintr (>= 1.0.0.9001), MASS, mboost, mco, mda, memoise, mlbench, mldr, mlrMBO, mmpf, modeltools, mRMRe, neuralnet, nnet, nodeHarvest (>= 0.7-3), numDeriv, pamr, pander, party, penalized (>= 0.9-47), pls, PMCMR (>= 4.1), praznik (>= 5.0.0), randomForest, randomForestSRC (>= 2.7.0), ranger (>= 0.8.0), rappdirs, refund, rex, rFerns, rgenoud, rknn, rmarkdown, ROCR, rotationForest, rpart, RRF, rrlda, rsm, RSNNS, rucrdtw, RWeka, sda, sf, smoof, sparseLDA, stepPlr, survAUC, svglite, SwarmSVM, testthat, tgp, TH.data, tsfeatures, vdiffr, wavelets, xgboost (>= 0.7)
# VignetteBuilder: knitr
# ByteCompile: yes
# Encoding: UTF-8
# LazyData: yes
# RoxygenNote: 7.0.2
# NeedsCompilation: yes
# Packaged: 2020-01-10 16:20:32 UTC; patrickschratz
# Author: Bernd Bischl [aut] (<https://orcid.org/0000-0001-6002-6980>), Michel Lang [aut] (<https://orcid.org/0000-0001-9754-0393>), Lars Kotthoff [aut], Julia Schiffner [aut], Jakob Richter [aut], Zachary Jones [aut], Giuseppe Casalicchio [aut] (<https://orcid.org/0000-0001-5324-5966>), Mason Gallo [aut], Patrick Schratz [aut, cre] (<https://orcid.org/0000-0003-0748-6624>), Jakob Bossek [ctb] (<https://orcid.org/0000-0002-4121-4668>), Erich Studerus [ctb] (<https://orcid.org/0000-0003-4233-0182>), Leonard Judt [ctb], Tobias Kuehn [ctb], Pascal Kerschke [ctb] (<https://orcid.org/0000-0003-2862-1418>), Florian Fendt [ctb], Philipp Probst [ctb] (<https://orcid.org/0000-0001-8402-6790>), Xudong Sun [ctb] (<https://orcid.org/0000-0003-3269-2307>), Janek Thomas [ctb] (<https://orcid.org/0000-0003-4511-6245>), Bruno Vieira [ctb], Laura Beggel [ctb] (<https://orcid.org/0000-0002-8872-8535>), Quay Au [ctb] (<https://orcid.org/0000-0002-5252-8902>), Martin Binder [ctb], Florian Pfisterer [ctb], Stefan Coors [ctb], Steve Bronder [ctb], Alexander Engelhardt [ctb], Christoph Molnar [ctb], Annette Spooner [ctb]
# Maintainer: Patrick Schratz <patrick.schratz@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-01-10 20:00:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
